from pathlib import Path
base = Path(r'C:\Users\Willyandi Wu\Documents\918payv3')

repls = {
    'index.html': [
        ('<html lang="en">','<html lang="zh-CN">'),
        ('<title>PayAdmin — Financial Management System</title>','<title>PayAdmin — 财务管理系统</title>'),
        ('<p>Financial Management System</p>','<p>财务管理系统</p>'),
        ('⚠ Please fill in all fields correctly.','⚠ 请正确填写所有字段。'),
        ('<label>Username</label>','<label>用户名</label>'),
        ('<label>Password</label>','<label>密码</label>'),
        ('<label>Google 2FA Code</label>','<label>Google 双重验证码</label>'),
        ('<button class="login-btn" onclick="doLogin()">Log In</button>','<button class="login-btn" onclick="doLogin()">登录</button>'),
        ('PayAdmin is a secure internal tool. Please login with your\n          administrator','PayAdmin 是内部安全工具。请使用管理员账号登录'),
        ('title="Toggle sidebar"','title="切换侧边栏"'),
        ('<div class="user-role">Administrator</div>','<div class="user-role">管理员</div>'),
        ('<div class="nav-section-label">Main</div>','<div class="nav-section-label">主页</div>'),
        ('<span class="nav-label">Dashboard</span>','<span class="nav-label">仪表盘</span>'),
        ('<div class="nav-section-label">Operations</div>','<div class="nav-section-label">操作</div>'),
        ('<span class="nav-label">Transaction Mgmt</span>','<span class="nav-label">交易管理</span>'),
        ('<span class="nav-label">Bank Mgmt</span>','<span class="nav-label">银行管理</span>'),
        ('<span class="nav-label">History</span>','<span class="nav-label">历史记录</span>'),
        ('<div class="nav-section-label">Analytics</div>','<div class="nav-section-label">分析</div>'),
        ('<span class="nav-label">Reports</span>','<span class="nav-label">报表</span>'),
        ('<div class="nav-section-label">Communication</div>','<div class="nav-section-label">沟通</div>'),
        ('<span class="nav-label">Chat</span>','<span class="nav-label">聊天</span>'),
        ('>🏠 Home</span','>🏠 首页</span'),
        ('>Dashboard</span','>仪表盘</span'),
        ('>Welcome, <strong id="topbar-username">admin</strong></span','>欢迎，<strong id="topbar-username">admin</strong></span'),
        ('>⛶ Full\n            </button>','>⛶ 全屏\n            </button>'),
        ('<button class="topbar-logout" onclick="doLogout()">✕ Logout</button>','<button class="topbar-logout" onclick="doLogout()">✕ 退出</button>'),
        ('⟳ Refresh','⟳ 刷新'),
        ('<p>Total Transactions</p>','<p>交易总数</p>'),
        ('🤖 AI Engine','🤖 AI 引擎'),
        ('>OFFLINE<','>离线<'),
        ('>START ENGINE<','>启动引擎<'),
        ('👤 Presence Admin','👤 在线管理员'),
        ('Loading presence...','正在加载在线状态...'),
        ('<p>Pending</p>','<p>待处理</p>'),
        ('<p>Completed</p>','<p>已完成</p>'),
        ('<p>Failed / Rejected</p>','<p>失败 / 已拒绝</p>'),
        ('<h3>📋 Recent Activity</h3>','<h3>📋 最近活动</h3>'),
        ('<div style="font-size: 12px; font-weight: 700">Reports</div>','<div style="font-size: 12px; font-weight: 700">报表</div>'),
        ('View reports ','查看报表 '),
        ('placeholder="Search TX ID..."','placeholder="搜索交易编号..."'),
        ('placeholder="Search Order ID..."','placeholder="搜索订单编号..."'),
        ('placeholder="Search Account No..."','placeholder="搜索账号..."'),
        ('placeholder="Search Account Name..."','placeholder="搜索账户姓名..."'),
        ('<option value="">All Status</option>','<option value="">全部状态</option>'),
        ('<option value="Pending">Pending</option>','<option value="Pending">待处理</option>'),
        ('<option value="Processing">Processing</option>','<option value="Processing">处理中</option>'),
        ('<option value="Completed">Completed</option>','<option value="Completed">已完成</option>'),
        ('<option value="Failed">Failed</option>','<option value="Failed">失败</option>'),
        ('<option value="">All Banks</option>','<option value="">全部银行</option>'),
        ('🔍 Search','🔍 搜索'),('🗑 Reset','🗑 重置'),('📅 Today','📅 今天'),('🕘 Yesterday','🕘 昨天'),
        ('title="Search"','title="搜索"'),
        ('<th>Completed</th>','<th>完成时间</th>'),
        ('<h2>History Transactions</h2>','<h2>交易历史</h2>'),
        ('<p>Completed & Failed transactions</p>','<p>已完成与失败的交易</p>'),
        ('title="Refresh History"','title="刷新历史记录"'),
        ('placeholder="Search Txn ID..."','placeholder="搜索交易编号..."'),
        ('<h2>📊 Reports</h2>','<h2>📊 报表</h2>'),
        ('View system reports and analytics','查看系统报表与分析'),
        ('Success rate and processing time by bank','按银行查看成功率与处理时间'),
        ('<h4>Failed Transactions</h4>','<h4>失败交易</h4>'),
        ('Rejected and failed transaction analysis','被拒与失败交易分析'),
        ('Processing time distribution report','处理时间分布报表'),
        ('<span id="sys-notice-text">Action completed.</span>','<span id="sys-notice-text">操作已完成。</span>'),
    ],
    'chat.html': [
        ('<html lang="en">','<html lang="zh-CN">'),
        ('<title>Chat Support</title>','<title>聊天支持</title>'),
        ('<h2>PayAdmin Chat</h2>','<h2>PayAdmin 聊天</h2>'),
        ('<p>Internal Security System</p>','<p>内部安全系统</p>'),
        ('⚠ Invalid credentials.','⚠ 凭证无效。'),
        ('<label>Email Address</label>','<label>电子邮箱</label>'),
        ('placeholder="Enter email..."','placeholder="输入邮箱..."'),
        ('<label>Password</label>','<label>密码</label>'),
        ('placeholder="Enter password..."','placeholder="输入密码..."'),
        ('<label>2FA Code</label>','<label>双重验证码</label>'),
        ('>Authenticate</button>','>验证登录</button>'),
        ('placeholder="Search"','placeholder="搜索"'),
        ('>📊 ABSENSI<','>📊 考勤<'),
        ('>Session tracking...<','>会话追踪中...<'),
        ('>❌ REJECT FAILED<','>❌ 拒绝 / 失败<'),
        ('>Submit error screenshots...<','>提交错误截图...<'),
        ('>👥 WORKER GROUP<','>👥 员工群组<'),
        ('>Admin discussion...<','>管理员讨论...<'),
        ('>Admin Online<','>在线管理员<'),
        ('>WORKER GROUP<','>员工群组<'),
        ('>online<','>在线<'),
        ('>Masuk</button>','>上班</button>'),
        ('>🏃 WC</button>','>🏃 洗手间</button>'),
        ('>🍴 Makan</button>','>🍴 用餐</button>'),
        ('>Pulang</button>','>下班</button>'),
        ('title="Add Attachment"','title="添加附件"'),
        ('placeholder="Message"','placeholder="输入消息"'),
        ('<span>Send Photo</span>','<span>发送图片</span>'),
        ('placeholder="Add a caption..."','placeholder="添加说明..."'),
    ],
    'reset.html': [
        ('<html lang="en">','<html lang="zh-CN">'),
        ('<title>PayAdmin - System Reset</title>','<title>PayAdmin - 系统重置</title>'),
        ('<h1>RESET DATABASE</h1>','<h1>重置数据库</h1>'),
        ('Tombol ini akan menghapus <strong>SELURUH</strong> data berikut:<br>\n        - Semua Transaksi (History)<br>\n        - Semua Log Aktivitas<br>\n        - Seluruh Pesan Chat &amp; Foto','此按钮将删除以下<strong>全部</strong>数据：<br>\n        - 所有交易（历史）<br>\n        - 所有活动日志<br>\n        - 所有聊天消息和图片'),
        ('>HAPUS SEMUA DATA</button>','>删除所有数据</button>'),
        ('const confirmed = confirm("⚠️ APAKAH ANDA BENAR-BENAR YAKIN? Data yang dihapus tidak bisa dikembalikan!");','const confirmed = confirm("⚠️ 你确定吗？删除后的数据无法恢复！");'),
        ('const doubleConfirmed = prompt("Tulis kata \'HAPUS\' (huruf besar) untuk melanjutkan:");','const doubleConfirmed = prompt("请输入“删除”以继续：");'),
        ('if (doubleConfirmed !== "HAPUS") {','if (doubleConfirmed !== "删除") {'),
        ('alert("Sandi salah. Reset dibatalkan.");','alert("口令错误，已取消重置。");'),
        ('btn.innerText = "Processing...";','btn.innerText = "处理中...";'),
        ('log("Deleting Transaction Logs...");','log("正在删除交易日志...");'),
        ('log("Deleting Transactions...");','log("正在删除交易记录...");'),
        ('log("Deleting Chat Messages...");','log("正在删除聊天消息...");'),
        ('log("Cleaning up Storage Bucket \'chat_images\'...");','log("正在清理存储桶 chat_images...");'),
        ('log("Warning: Storage cleanup skipped", "#eab308");','log("警告：已跳过存储清理", "#eab308");'),
        ('if (delError) log("Warning: Storage delete failed: " + delError.message, "#f43f5e");','if (delError) log("警告：存储删除失败：" + delError.message, "#f43f5e");'),
        ('else log(`Storage: ${files.length} images deleted.`, "#10b981");','else log(`存储：已删除 ${files.length} 张图片。`, "#10b981");'),
        ('log("Storage: No images found.", "#94a3b8");','log("存储：未找到图片。", "#94a3b8");'),
        ('log("✅ SYSTEM RESET COMPLETE!", "#10b981");','log("✅ 系统重置完成！", "#10b981");'),
        ('alert("Semua data telah dihapus bersih!");','alert("所有数据已彻底删除！");'),
        ('log("❌ ERROR: " + err.message, "#f43f5e");','log("❌ 错误：" + err.message, "#f43f5e");'),
        ('alert("Terjadi kesalahan saat reset: " + err.message);','alert("重置时发生错误：" + err.message);'),
        ('btn.innerText = "HAPUS SEMUA DATA";','btn.innerText = "删除所有数据";'),
    ],
    'proof.html': [
        ('<html lang="en">','<html lang="zh-CN">'),
        ('✅ Completed','✅ 已完成'),
        ('PayAdmin Financial Management System','PayAdmin 财务管理系统'),
    ],
    'script.js': [
        ('${msg || "No transactions found."}','${msg || "未找到交易记录。"}'),
        ('dashboard: "Dashboard",','dashboard: "仪表盘",'),
        ('transactions: "Transaction Management",','transactions: "交易管理",'),
        ('banks: "Bank Management",','banks: "银行管理",'),
        ('reports: "Reports",','reports: "报表",'),
        ('showNotice("History refreshed", "success");','showNotice("历史记录已刷新", "success");'),
    ],
}

for fn, pairs in repls.items():
    p = base / fn
    text = p.read_text(encoding='utf-8')
    orig = text
    for old, new in pairs:
        text = text.replace(old, new)
    if text != orig:
        p.write_text(text, encoding='utf-8')
        print(f'UPDATED {fn}')
    else:
        print(f'NOCHANGE {fn}')
